### ISSUE TITLE
Ghostwriter won't open

### ISSUE THREAD

**Issue by ThowV** [michelolvera/vs-ghostwriter#5]
Good day Michelolvera,

I recently installed Ghostwriter using both the .exe and the z7.
I have a problem with both methods though. The application won't run. It doesn't show up in the taskmanager.
I have installed Ghostwriter using Admin privileges and I've restarted my machine before opening the application.
Any idea why this problem might occur?
Hope we can resolve the issue.

**Comment by michelolvera** [comment]
I understand, you could give me more information, such as Windows and Visual C ++. In any case I will try to replicate it in a virtual machine with a new copy of Windows 7.

**Comment by twinysam** [comment]
I have the exact same problem. Windows 7 Ultimate 64bit. Previous version worked perfectly, but this one won't open. The installer added an upgrade to Visual C++ but I'm not sure where to look for the exact version. I'm available to provide any extra info.

**Comment by ThowV** [comment]
Hi, sorry for the late response. I'm using Windows, this version to be exact: May 14, 2019—KB4499167 (OS Build 17134.765). I have the following C++ versions on my machine: 
![image](https://user-images.githubusercontent.com/40771176/58016398-cdd34380-7afd-11e9-92ea-ea974ca98314.png)

**Comment by ThowV** [comment]
The older version does work so I'll use that untill the problem gets resolved!

**Comment by michelolvera** [comment]
An apology for the inconvenience, I'm working on it, however my work leaves me very little free time, give me a couple of days to fix it.

I'm almost sure that the problem is a missing library (DLL), I use the latest version of Windows 10 and it works well, if someone finds a solution please comment here.

**Comment by seik0ixtem** [comment]
Tried on Windows 10 - just does not start. Maybe Windows not latest update.
On Windows 8.1 - doesn't start, but with general error message.

In attachment ProcMon log with "ghostwriter.exe" filter. 
Up to the moment where error appears.
[procmon_ghostwriter_err.zip](https://github.com/michelolvera/vs-ghostwriter/files/3202237/procmon_ghostwriter_err.zip)

**Comment by michelolvera** [comment]
Solved, you can download the new installer [here](https://github.com/michelolvera/vs-ghostwriter/releases/tag/1.8.0), QtWebEngine requires some new files that had not been included in the first installer, it worked for me since the executable was looking for the files in the exact location where I have them.

In case you find any problem, let me know.

**Comment by twinysam** [comment]
Thanks a lot for your good work with these Windows builds!
